CREATE TABLE  "IMP_DEUTSCHE_BANK" 
   (	"BOOKING_DATE" DATE, 
	"VALUE_DATE" DATE, 
	"TRANSACTION_TYPE" VARCHAR2(50), 
	"BENEFICIARY___ORIGINATOR" VARCHAR2(50), 
	"PAYMENT_DETAILS" VARCHAR2(255), 
	"IBAN" VARCHAR2(50), 
	"BIC" VARCHAR2(50), 
	"CUSTOMER_REFERENCE" VARCHAR2(255), 
	"MANDATE_REFERENCE" VARCHAR2(50), 
	"CREDITOR_ID" VARCHAR2(50), 
	"COMPENSATION_AMOUNT" VARCHAR2(4000), 
	"ORIGINAL_AMOUNT" VARCHAR2(4000), 
	"ULTIMATE_CREDITOR" VARCHAR2(4000), 
	"NUMBER_OF_TRANSACTIONS" VARCHAR2(4000), 
	"NUMBER_OF_CHEQUES" VARCHAR2(4000), 
	"DEBIT" VARCHAR2(20), 
	"CREDIT" VARCHAR2(4000), 
	"CURRENCY" VARCHAR2(50), 
	"BANK_CODE" VARCHAR2(20), 
	"ACCOUNT_NO" VARCHAR2(20)
   )
/


COMMENT ON TABLE IMP_DEUTSCHE_BANK IS 'import table for english CSV version of Deutsche Bank';