CREATE TABLE  "IMP_HVB_CSV_DEUTSCH" 
   (	"KONTONUMMER" VARCHAR2(100 CHAR), 
	"BUCHUNGSDATUM" DATE, 
	"VALUTA" DATE, 
	"EMPFAENGER1" VARCHAR2(100 CHAR), 
	"EMPFAENGER2" VARCHAR2(100 CHAR), 
	"VERWENDUNGSZWECK" VARCHAR2(500 CHAR), 
	"BETRAG" VARCHAR2(100 CHAR), 
	"WAEHRUNG" VARCHAR2(100 CHAR), 
	"INSERT_DT" DATE DEFAULT sysdate, 
	"APEX_SESS_ID" NUMBER
   )
/
