CREATE TABLE  imp_deutsche_bank_legacy  
   (	"KTO_NR" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"VORG_ID" NUMBER(12,0) NOT NULL ENABLE, 
	"VORG_DAT" DATE NOT NULL ENABLE, 
	"WERT_DAT" DATE NOT NULL ENABLE, 
	"SUMME" NUMBER(12,2) NOT NULL ENABLE, 
	"TEXT" VARCHAR2(1000 BYTE), 
	"AKAT" VARCHAR2(2 BYTE), 
	"MAN_UPD" CHAR(1 BYTE), 
	"LOAD_DT" DATE DEFAULT sysdate, 
	"UMSATZ_ART" VARCHAR2(30 BYTE)
	, 	 PRIMARY KEY ("VORG_ID")
	);